# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imdb_api.Genre'),
        ),
    ]
